apiVersion: v1
data:
  redis.sh: |
    #!/bin/sh
    set -eo pipefail

    host="$(hostname -i || echo '127.0.0.1')"

    if ping="$(redis-cli -h "$host" ping)" && [ "$ping" = 'PONG' ]; then
    	exit 0
    fi

    exit 1
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: redis
  name: redis-cm0
