apiVersion: batch/v1
kind: Job
metadata:
  name: seed
spec:
  template:
    metadata:
      labels:
        app: seed
    spec:
      restartPolicy: OnFailure
      containers:
        - name: seed
          image: vote-app/seed
