apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: seed
  name: seed
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: seed
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.35.0 (HEAD)
      labels:
        io.kompose.service: seed
    spec:
      containers:
        - image: seed
          name: seed
      restartPolicy: Always
