apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-healthcheck-script
data:
  redis.sh: |
    #!/bin/sh
    set -eo pipefail

    host="$(hostname -i || echo '127.0.0.1')"

    if ping="$(redis-cli -h "$host" ping)" && [ "$ping" = 'PONG' ]; then
      exit 0
    fi

    exit 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis-healthcheck
              mountPath: /usr/local/bin/redis-healthcheck.sh
              subPath: redis.sh
          livenessProbe:
            exec:
              command: ["sh", "/usr/local/bin/redis-healthcheck.sh"]
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: redis-healthcheck
          configMap:
            name: redis-healthcheck-script
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: redis
  ports:
    - port: 6379
