apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - namespace.yaml
  - hpa.yaml
  - postgres.yaml
  
namespace: production

labels:
  - pairs:
      environment: production
