---
- name: Ajouter la clé GPG du dépôt PostgreSQL
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- name: Ajouter le dépôt PostgreSQL 15
  ansible.builtin.apt_repository:
    repo: "deb http://apt.postgresql.org/pub/repos/apt {{ ansible_distribution_release }}-pgdg main"
    filename: 'pgdg'
    state: present

- name: Mettre à jour le cache APT
  ansible.builtin.apt:
    update_cache: yes

- name: Installer PostgreSQL 15 et les paquets nécessaires
  ansible.builtin.apt:
    name: "{{ postgresql_packages }}"
    state: present
    update_cache: yes